In [1]:
import torch

In [2]:
#z = b+w1x1 +w2x2, Xw

In [3]:
X = torch.tensor([[1,0,0],[1,1,0],[1,0,1],[1,1,1]], dtype = torch.float32)

torch.tensor - 判断你的输入数据是什么类型，然后根据你输入的数据类型来确定中的数据类型

torch.Tensor - 无论你输入什么数据，都无脑使用float32

In [4]:
torch.Tensor([[1,0,0],[1,1,0],[1,0,1],[1,1,1]])

tensor([[1., 0., 0.],
        [1., 1., 0.],
        [1., 0., 1.],
        [1., 1., 1.]])

In [5]:
X

tensor([[1., 0., 0.],
        [1., 1., 0.],
        [1., 0., 1.],
        [1., 1., 1.]])

In [6]:
X.float()

tensor([[1., 0., 0.],
        [1., 1., 0.],
        [1., 0., 1.],
        [1., 1., 1.]])

In [7]:
X.dtype

torch.float32

In [8]:
X.shape

torch.Size([4, 3])

In [9]:
w = torch.tensor([-0.2,0.15,0.15]) #(b,w1,w2)

In [10]:
w.shape

torch.Size([3])

In [11]:
X*w 

tensor([[-0.2000,  0.0000,  0.0000],
        [-0.2000,  0.1500,  0.0000],
        [-0.2000,  0.0000,  0.1500],
        [-0.2000,  0.1500,  0.1500]])

In [12]:
#numpy,dot

In [13]:
def LinearR(X,w):
    zhat = torch.mv(X,w)
    return zhat

In [14]:
X.dtype #long = int64

torch.float32

In [15]:
w.dtype

torch.float32

In [16]:
X

tensor([[1., 0., 0.],
        [1., 1., 0.],
        [1., 0., 1.],
        [1., 1., 1.]])

In [17]:
w

tensor([-0.2000,  0.1500,  0.1500])

In [18]:
X

tensor([[1., 0., 0.],
        [1., 1., 0.],
        [1., 0., 1.],
        [1., 1., 1.]])

In [19]:
z = torch.tensor([[-0.2],[-0.05], [-0.05],[0.1]], dtype = torch.float32)

In [20]:
z

tensor([[-0.2000],
        [-0.0500],
        [-0.0500],
        [ 0.1000]])

In [21]:
z.ndim

2

In [22]:
z.shape

torch.Size([4, 1])

In [23]:
z

tensor([[-0.2000],
        [-0.0500],
        [-0.0500],
        [ 0.1000]])

In [24]:
z = z.view([4])

In [25]:
z

tensor([-0.2000, -0.0500, -0.0500,  0.1000])

In [26]:
zhat = LinearR(X,w)

In [27]:
zhat

tensor([-0.2000, -0.0500, -0.0500,  0.1000])

In [28]:
zhat == z

tensor([ True, False, False, False])

In [29]:
zhat.dtype

torch.float32

In [30]:
z.dtype

torch.float32

In [31]:
#SSE = SIGMA（(真实值 - 预测值)*2）

In [32]:
SSE = sum((zhat - z)**2)

In [33]:
SSE

tensor(8.3267e-17)

In [34]:
#设置显示精度，再来看yhat与y_reg
#torch.set_printoptions(precision=30) #看小数点后面30位的情况

In [35]:
zhat

tensor([-0.2000, -0.0500, -0.0500,  0.1000])

In [36]:
z

tensor([-0.2000, -0.0500, -0.0500,  0.1000])

In [37]:
# float32由于只保留32位，所以精确性会有一些问题
# torch.mv这个函数在进行计算的时候，内部计算时会出现一些很微小的精度问题

In [38]:
preds = torch.ones(300,68,64,64) * 0.1
preds.sum() * 10

tensor(83558432.)

In [39]:
preds = torch.ones(300,68,64,64)
preds.sum()

tensor(83558400.)

In [40]:
preds = torch.ones(300,68,64,64,dtype = torch.float64) *0.1
preds.sum() * 10

tensor(83558400.0000, dtype=torch.float64)

In [41]:
torch.allclose(zhat,z)

True

In [42]:
import torch

X = torch.tensor([[1,0,0],[1,1,0],[1,0,1],[1,1,1]]
                 , dtype = torch.float32)
w = torch.tensor([-0.2,0.15,0.15],dtype = torch.float32)

In [43]:
z = torch.tensor([[-0.2],[-0.05], [-0.05],[0.1]], dtype = torch.float32)

In [44]:
def LinearR(X,w):
    zhat = torch.mv(X,w)
    return zhat

In [45]:
zhat = LinearR(X,w)

In [46]:
zhat

tensor([-0.2000, -0.0500, -0.0500,  0.1000])

In [47]:
import torch

In [48]:
X = torch.tensor([[0,0],[1,0],[0,1],[1,1]],dtype = torch.float32)

In [49]:
X

tensor([[0., 0.],
        [1., 0.],
        [0., 1.],
        [1., 1.]])

In [50]:
#w

In [51]:
torch.random.manual_seed(250) #人为设置随机数种子
#实例化nn.Linear
output = torch.nn.Linear(2,1)
#上一层的神经元个数（上一层的神经元中，给现在这一层传输数据的神经元的个数）
#这一层的神经元个数（接收传输数据的神经元的个数）

In [52]:
output.weight

Parameter containing:
tensor([[ 0.6838, -0.5888]], requires_grad=True)

In [53]:
output.bias

Parameter containing:
tensor([0.4269], requires_grad=True)

In [54]:
zhat = output(X)

In [55]:
zhat.shape

torch.Size([4, 1])

In [56]:
zhat

tensor([[ 0.4269],
        [ 1.1107],
        [-0.1619],
        [ 0.5219]], grad_fn=<AddmmBackward>)

In [57]:
import torch

In [58]:
X = torch.tensor([[1,0,0],[1,1,0],[1,0,1],[1,1,1]], dtype = torch.float32)

In [59]:
andgate = torch.tensor([[0],[0],[0],[1]], dtype = torch.float32)

In [60]:
w = torch.tensor([-0.2, 0.15,0.15],dtype =torch.float32)

In [61]:
def LogisticR(X,w):
    zhat = torch.mv(X,w)
    sigma = 1/(1+torch.exp(-zhat))
    #sigma = torch.sigmoid(zhat)
    andhat = torch.tensor([int(x) for x in sigma >= 0.5], dtype = torch.float32)
    return sigma, andhat

In [62]:
sigma, andhat = LogisticR(X,w)

In [63]:
sigma

tensor([0.4502, 0.4875, 0.4875, 0.5250])

In [64]:
andhat

tensor([0., 0., 0., 1.])

In [65]:
andgate

tensor([[0.],
        [0.],
        [0.],
        [1.]])

In [66]:
import torch
from torch.nn import functional as F

In [67]:
#F.sigmoid()

In [68]:
X = torch.tensor([[0,0],[1,0],[0,1],[1,1]],dtype=torch.float32)

In [69]:
torch.random.manual_seed(420)
dense = torch.nn.Linear(2,1)
zhat = dense(X)
sigma = F.sigmoid(zhat)
y = [int(x) for x in sigma >=0.5]

C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\functional.py:1709: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")


In [70]:
y

[1, 1, 1, 1]

In [71]:
zhat

tensor([[0.6730],
        [1.1048],
        [0.2473],
        [0.6792]], grad_fn=<AddmmBackward>)

In [72]:
#符号函数、阶跃函数sign

In [73]:
torch.sign(zhat)

tensor([[1.],
        [1.],
        [1.],
        [1.]], grad_fn=<SignBackward>)

In [74]:
#ReLU

In [75]:
F.relu(zhat)

tensor([[0.6730],
        [1.1048],
        [0.2473],
        [0.6792]], grad_fn=<ReluBackward0>)

In [76]:
#tanh

In [77]:
torch.tanh(zhat)

tensor([[0.5869],
        [0.8022],
        [0.2424],
        [0.5910]], grad_fn=<TanhBackward>)

In [78]:
z = torch.tensor([1010,100,990], dtype=torch.float32)

In [79]:
#z = torch.tensor([10,9,8], dtype=torch.float32)

In [80]:
torch.exp(z)/torch.sum(torch.exp(z))

tensor([nan, nan, nan])

In [81]:
torch.softmax(z,0)

tensor([1.0000e+00, 0.0000e+00, 2.0612e-09])

In [82]:
z = torch.tensor([3,3.5,2], dtype=torch.float32)

In [83]:
torch.exp(z)/torch.sum(torch.exp(z))

tensor([0.3315, 0.5465, 0.1220])

In [84]:
torch.softmax(z,0).sum()

tensor(1.0000)

In [85]:
torch.softmax(z,-1) #你希望进行softmax运算的那个维度的索引

tensor([0.3315, 0.5465, 0.1220])

In [86]:
z #正向是0，负向是-1

tensor([3.0000, 3.5000, 2.0000])

In [87]:
s = torch.tensor([[[1,2,4,5],[3,4,4,5],[5,6,4,5]]
                  ,[[5,6,4,5],[7,8,4,5],[9,10,4,5]]], dtype=torch.float32)

In [88]:
s

tensor([[[ 1.,  2.,  4.,  5.],
         [ 3.,  4.,  4.,  5.],
         [ 5.,  6.,  4.,  5.]],

        [[ 5.,  6.,  4.,  5.],
         [ 7.,  8.,  4.,  5.],
         [ 9., 10.,  4.,  5.]]])

In [89]:
s.shape

torch.Size([2, 3, 4])

In [90]:
s.shape[-3]

2

In [91]:
s.shape[-2]

3

In [92]:
s.shape[-1]

4

In [93]:
s.shape #

torch.Size([2, 3, 4])

In [99]:
s

tensor([[[ 1.,  2.,  4.,  5.],
         [ 3.,  4.,  4.,  5.],
         [ 5.,  6.,  4.,  5.]],

        [[ 5.,  6.,  4.,  5.],
         [ 7.,  8.,  4.,  5.],
         [ 9., 10.,  4.,  5.]]])

In [102]:
import numpy as np

In [110]:
s

tensor([[[ 1.,  2.,  4.,  5.],
         [ 3.,  4.,  4.,  5.],
         [ 5.,  6.,  4.,  5.]],

        [[ 5.,  6.,  4.,  5.],
         [ 7.,  8.,  4.,  5.],
         [ 9., 10.,  4.,  5.]]])

In [111]:
torch.softmax(s,dim=0)

tensor([[[0.0180, 0.0180, 0.5000, 0.5000],
         [0.0180, 0.0180, 0.5000, 0.5000],
         [0.0180, 0.0180, 0.5000, 0.5000]],

        [[0.9820, 0.9820, 0.5000, 0.5000],
         [0.9820, 0.9820, 0.5000, 0.5000],
         [0.9820, 0.9820, 0.5000, 0.5000]]])

In [105]:
molecular = np.exp(1)+np.exp(3)+np.exp(5)
denominator = molecular + np.exp(5)+np.exp(7)+np.exp(9)

In [107]:
molecular/denominator

0.017986209962091555

In [108]:
molecular2 = np.exp(5)+np.exp(7)+np.exp(9)

In [109]:
molecular2/denominator

0.9820137900379083

In [104]:
np.exp(1)+np.exp(3)+np.exp(5)/(np.exp(9)+np.exp(21))

6.144174602214718e-06

In [100]:
s[0]

tensor([[1., 2., 4., 5.],
        [3., 4., 4., 5.],
        [5., 6., 4., 5.]])

In [101]:
s[1]

tensor([[ 5.,  6.,  4.,  5.],
        [ 7.,  8.,  4.,  5.],
        [ 9., 10.,  4.,  5.]])

tensor([[[0.0180, 0.0180, 0.5000, 0.5000],
         [0.0180, 0.0180, 0.5000, 0.5000],
         [0.0180, 0.0180, 0.5000, 0.5000]],

        [[0.9820, 0.9820, 0.5000, 0.5000],
         [0.9820, 0.9820, 0.5000, 0.5000],
         [0.9820, 0.9820, 0.5000, 0.5000]]])

In [95]:
torch.softmax(s,dim=1)

tensor([[[0.0159, 0.0159, 0.3333, 0.3333],
         [0.1173, 0.1173, 0.3333, 0.3333],
         [0.8668, 0.8668, 0.3333, 0.3333]],

        [[0.0159, 0.0159, 0.3333, 0.3333],
         [0.1173, 0.1173, 0.3333, 0.3333],
         [0.8668, 0.8668, 0.3333, 0.3333]]])

In [96]:
torch.softmax(s,dim=2)

tensor([[[0.0128, 0.0347, 0.2562, 0.6964],
         [0.0723, 0.1966, 0.1966, 0.5344],
         [0.1966, 0.5344, 0.0723, 0.1966]],

        [[0.1966, 0.5344, 0.0723, 0.1966],
         [0.2562, 0.6964, 0.0128, 0.0347],
         [0.2671, 0.7262, 0.0018, 0.0049]]])