In [3]:
import torch
from torch.nn import MSELoss #Class

In [4]:
yhat = torch.randn(size=(50,),dtype=torch.float32)
y = torch.randn(size=(50,),dtype=torch.float32)

In [ ]:
criterion /loss

In [8]:
criterion = MSELoss(reduction = "sum")

In [9]:
loss = criterion(yhat,y)

In [10]:
loss

tensor(89.0168)

In [ ]:
MSEloss(reduction = "mean"/"sum") #MSE #SSE

In [20]:
import torch

In [ ]:
#loss = -(y*ln(sigma) + (1-y)*ln(1-sigma))

In [ ]:
#y - 真实标签
#sigma - sigmoid(z)
#z = Xw
#X , w
#m 样本量

In [22]:
m = 3*pow(10,3)

torch.random.manual_seed(420)
X = torch.rand((m,4),dtype=torch.float32)
w = torch.rand((4,1),dtype=torch.float32)
y = torch.randint(low=0,high=2,size=(m,1),dtype=torch.float32)
zhat = torch.mm(X,w)
sigma = torch.sigmoid(zhat)

In [24]:
sigma.shape

In [ ]:
#loss = -(y*ln(sigma) + (1-y)*ln(1-sigma))

In [35]:
loss = -(1/m)*sum(y*torch.log(sigma) + (1-y)*torch.log(1-sigma))

In [ ]:
#total loss

In [36]:
loss

tensor([0.7962])

In [40]:
import time

In [72]:
m = 3*pow(10,3)

In [73]:
X = torch.rand((m,4),dtype=torch.float32)
w = torch.rand((4,1),dtype=torch.float32)
y = torch.randint(low=0,high=2,size=(m,1),dtype=torch.float32)
zhat = torch.mm(X,w)
sigma = torch.sigmoid(zhat)

In [68]:
X.shape

torch.Size([3000, 4])

In [69]:
start = time.time() #捕获现在的时间
loss1 = -(1/m)*sum(y*torch.log(sigma) + (1-y)*torch.log(1-sigma))
now = time.time() #以秒计
print(now - start)

0.051853179931640625


In [70]:
start = time.time()
loss2 = -(1/m)*torch.sum(y*torch.log(sigma) + (1-y)*torch.log(1-sigma))
now = time.time() #以秒计
print(now - start)

0.000997304916381836


In [71]:
import torch.nn as nn

In [79]:
criterion = nn.BCELoss(reduction = "mean") #实例化
loss = criterion(sigma,y)

In [80]:
loss

tensor(0.8951)

In [81]:
criterion2 = nn.BCEWithLogitsLoss(reduction = "sum")

In [82]:
loss = criterion2(zhat, y)

In [83]:
loss

tensor(2685.3774)

In [84]:
criterion2 = nn.BCEWithLogitsLoss(reduction = "none")

In [85]:
loss = criterion2(zhat, y)

In [87]:
loss.shape

torch.Size([3000, 1])

In [129]:
import torch
import torch.nn as nn

In [130]:
m = 3*pow(10,3)

In [142]:
torch.random.manual_seed(420)
X = torch.rand((m,4),dtype=torch.float32)
w = torch.rand((4,3),dtype=torch.float32)
y = torch.randint(low=0,high=3,size=(m,),dtype=torch.float32)

In [132]:
zhat = torch.mm(X,w)

In [ ]:
#sigma = torch.softmax(zhat)

In [ ]:
#logsoftmax - log + softmax, 输入:zhat

In [ ]:
#NLLLoss()

In [135]:
logsm = nn.LogSoftmax(dim=1)

In [136]:
logsigma = logsm(zhat)

In [138]:
logsigma

tensor([[-1.1139, -0.8802, -1.3585],
        [-1.0558, -0.8982, -1.4075],
        [-1.0920, -1.0626, -1.1430],
        ...,
        [-1.0519, -0.9180, -1.3805],
        [-1.0945, -1.1219, -1.0798],
        [-1.0276, -0.8891, -1.4649]])

In [139]:
criterion = nn.NLLLoss()

In [143]:
y

tensor([2., 2., 2.,  ..., 2., 2., 2.])

In [145]:
criterion(logsigma, y.long())

tensor(1.1147)

In [146]:
criterion = nn.CrossEntropyLoss()

In [147]:
criterion(zhat,y.long())

tensor(1.1147)